[workspace]
resolver = "3"
members = [
    "hc32f448",
    "hc32f460",
]

[package]
name = "hc32_driver_sys"
version = "0.1.0"
edition = "2024"
description = "Provide driver function binding for HDSC's HC32 series MCU."
keywords = ["HC32", "bindgen", "no_std", "bare-metal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/823984418/hc32_driver_sys"

[dependencies]

[dependencies.anyhow]
version = "1.0.102"

[dependencies.cc]
version = "1.2.63"

[dependencies.bindgen]
version = "0.72.1"

[dependencies.lang-c]
path = "../lang-c"
