/* automatically generated by rust-bindgen 0.72.1 */

pub const RMU_FLAG_PWR_ON: u32 = 1;
pub const RMU_FLAG_PIN: u32 = 2;
pub const RMU_FLAG_BROWN_OUT: u32 = 4;
pub const RMU_FLAG_PVD1: u32 = 8;
pub const RMU_FLAG_PVD2: u32 = 16;
pub const RMU_FLAG_WDT: u32 = 32;
pub const RMU_FLAG_SWDT: u32 = 64;
pub const RMU_FLAG_PWR_DOWN: u32 = 128;
pub const RMU_FLAG_SW: u32 = 256;
pub const RMU_FLAG_MPU_ERR: u32 = 512;
pub const RMU_FLAG_RAM_PARITY_ERR: u32 = 1024;
pub const RMU_FLAG_RAM_ECC: u32 = 2048;
pub const RMU_FLAG_CLK_ERR: u32 = 4096;
pub const RMU_FLAG_XTAL_ERR: u32 = 8192;
pub const RMU_FLAG_CPU_LOCKUP: u32 = 16384;
pub const RMU_FLAG_MX: u32 = 1073741824;
pub const RMU_FLAG_ALL: u32 = 1073774591;
pub const RMU_FRST0_PERIPH_KEY: u32 = 8192;
pub const RMU_FRST0_PERIPH_DMA1: u32 = 16384;
pub const RMU_FRST0_PERIPH_DMA2: u32 = 32768;
pub const RMU_FRST0_PERIPH_FCM: u32 = 65536;
pub const RMU_FRST0_PERIPH_AOS: u32 = 131072;
pub const RMU_FRST0_PERIPH_CTC: u32 = 262144;
pub const RMU_FRST0_PERIPH_AES: u32 = 1048576;
pub const RMU_FRST0_PERIPH_HASH: u32 = 2097152;
pub const RMU_FRST0_PERIPH_TRNG: u32 = 4194304;
pub const RMU_FRST0_PERIPH_CRC: u32 = 8388608;
pub const RMU_FRST0_PERIPH_DCU1: u32 = 16777216;
pub const RMU_FRST0_PERIPH_DCU2: u32 = 33554432;
pub const RMU_FRST0_PERIPH_DCU3: u32 = 67108864;
pub const RMU_FRST0_PERIPH_DCU4: u32 = 134217728;
pub const RMU_FRST0_PERIPH_ALL: u32 = 267902976;
pub const RMU_FRST1_PERIPH_QSPI: u32 = 8;
pub const RMU_FRST1_PERIPH_SPI1: u32 = 65536;
pub const RMU_FRST1_PERIPH_SPI2: u32 = 131072;
pub const RMU_FRST1_PERIPH_SPI3: u32 = 262144;
pub const RMU_FRST1_PERIPH_ALL: u32 = 458760;
pub const RMU_FRST2_PERIPH_TMR6: u32 = 1;
pub const RMU_FRST2_PERIPH_TMR4: u32 = 1024;
pub const RMU_FRST2_PERIPH_TMR0: u32 = 4096;
pub const RMU_FRST2_PERIPH_EMB: u32 = 32768;
pub const RMU_FRST2_PERIPH_TMRA: u32 = 1048576;
pub const RMU_FRST2_PERIPH_ALL: u32 = 1086465;
pub const RMU_FRST3_PERIPH_ADC1: u32 = 1;
pub const RMU_FRST3_PERIPH_ADC2: u32 = 2;
pub const RMU_FRST3_PERIPH_ADC3: u32 = 4;
pub const RMU_FRST3_PERIPH_DAC: u32 = 16;
pub const RMU_FRST3_PERIPH_CMP1_2: u32 = 256;
pub const RMU_FRST3_PERIPH_CMP3_4: u32 = 512;
pub const RMU_FRST3_PERIPH_SMC: u32 = 65536;
pub const RMU_FRST3_PERIPH_USART1: u32 = 1048576;
pub const RMU_FRST3_PERIPH_USART2: u32 = 2097152;
pub const RMU_FRST3_PERIPH_USART3: u32 = 4194304;
pub const RMU_FRST3_PERIPH_USART4: u32 = 8388608;
pub const RMU_FRST3_PERIPH_USART5: u32 = 16777216;
pub const RMU_FRST3_PERIPH_USART6: u32 = 33554432;
pub const RMU_FRST3_PERIPH_ALL: u32 = 66126615;
pub const en_functional_state_t_DISABLE: en_functional_state_t = 0;
pub const en_functional_state_t_ENABLE: en_functional_state_t = 1;
#[doc = " @brief Functional state"]
pub type en_functional_state_t = ::core::ffi::c_uint;
pub const en_flag_status_t_RESET: en_flag_status_t = 0;
pub const en_flag_status_t_SET: en_flag_status_t = 1;
#[doc = " @brief Flag status"]
pub type en_flag_status_t = ::core::ffi::c_uint;
unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup RMU_Global_Functions\n @{"]
    pub fn RMU_GetStatus(u32RmuResetCause: u32) -> en_flag_status_t;
    pub fn RMU_ClearStatus();
    pub fn RMU_CPULockUpCmd(enNewState: en_functional_state_t);
    pub fn RMU_Frst0PeriphReset(u32Frst0Periph: u32) -> i32;
    pub fn RMU_Frst1PeriphReset(u32Frst1Periph: u32) -> i32;
    pub fn RMU_Frst2PeriphReset(u32Frst2Periph: u32) -> i32;
    pub fn RMU_Frst3PeriphReset(u32Frst3Periph: u32) -> i32;
}
