/* automatically generated by rust-bindgen 0.72.1 */

pub const FCG0_PERIPH_SRAMH: u32 = 1;
pub const FCG0_PERIPH_SRAM0: u32 = 16;
pub const FCG0_PERIPH_SRAMB: u32 = 1024;
pub const FCG0_PERIPH_KEY: u32 = 8192;
pub const FCG0_PERIPH_DMA1: u32 = 16384;
pub const FCG0_PERIPH_DMA2: u32 = 32768;
pub const FCG0_PERIPH_FCM: u32 = 65536;
pub const FCG0_PERIPH_AOS: u32 = 131072;
pub const FCG0_PERIPH_CTC: u32 = 262144;
pub const FCG0_PERIPH_AES: u32 = 1048576;
pub const FCG0_PERIPH_HASH: u32 = 2097152;
pub const FCG0_PERIPH_TRNG: u32 = 4194304;
pub const FCG0_PERIPH_CRC: u32 = 8388608;
pub const FCG0_PERIPH_DCU1: u32 = 16777216;
pub const FCG0_PERIPH_DCU2: u32 = 33554432;
pub const FCG0_PERIPH_DCU3: u32 = 67108864;
pub const FCG0_PERIPH_DCU4: u32 = 134217728;
pub const FCG1_PERIPH_MCAN1: u32 = 1;
pub const FCG1_PERIPH_MCAN2: u32 = 2;
pub const FCG1_PERIPH_QSPI: u32 = 8;
pub const FCG1_PERIPH_I2C1: u32 = 16;
pub const FCG1_PERIPH_I2C2: u32 = 32;
pub const FCG1_PERIPH_SPI1: u32 = 65536;
pub const FCG1_PERIPH_SPI2: u32 = 131072;
pub const FCG1_PERIPH_SPI3: u32 = 262144;
pub const FCG2_PERIPH_TMR6_1: u32 = 1;
pub const FCG2_PERIPH_TMR6_2: u32 = 2;
pub const FCG2_PERIPH_TMR4_1: u32 = 512;
pub const FCG2_PERIPH_TMR4_2: u32 = 1024;
pub const FCG2_PERIPH_TMR4_3: u32 = 2048;
pub const FCG2_PERIPH_TMR0_1: u32 = 4096;
pub const FCG2_PERIPH_TMR0_2: u32 = 8192;
pub const FCG2_PERIPH_EMB: u32 = 32768;
pub const FCG2_PERIPH_TMRA_1: u32 = 1048576;
pub const FCG2_PERIPH_TMRA_2: u32 = 2097152;
pub const FCG2_PERIPH_TMRA_3: u32 = 4194304;
pub const FCG2_PERIPH_TMRA_4: u32 = 8388608;
pub const FCG2_PERIPH_TMRA_5: u32 = 16777216;
pub const FCG3_PERIPH_ADC1: u32 = 1;
pub const FCG3_PERIPH_ADC2: u32 = 2;
pub const FCG3_PERIPH_ADC3: u32 = 4;
pub const FCG3_PERIPH_DAC: u32 = 16;
pub const FCG3_PERIPH_CMP1_2: u32 = 256;
pub const FCG3_PERIPH_CMP3_4: u32 = 512;
pub const FCG3_PERIPH_SMC: u32 = 65536;
pub const FCG3_PERIPH_USART1: u32 = 1048576;
pub const FCG3_PERIPH_USART2: u32 = 2097152;
pub const FCG3_PERIPH_USART3: u32 = 4194304;
pub const FCG3_PERIPH_USART4: u32 = 8388608;
pub const FCG3_PERIPH_USART5: u32 = 16777216;
pub const FCG3_PERIPH_USART6: u32 = 33554432;
pub const FCG_FCG0_PERIPH_MASK: u32 = 267904017;
pub const FCG_FCG1_PERIPH_MASK: u32 = 458811;
pub const FCG_FCG2_PERIPH_MASK: u32 = 32554499;
pub const FCG_FCG3_PERIPH_MASK: u32 = 66126615;
pub const en_functional_state_t_DISABLE: en_functional_state_t = 0;
pub const en_functional_state_t_ENABLE: en_functional_state_t = 1;
#[doc = " @brief Functional state"]
pub type en_functional_state_t = ::core::ffi::c_uint;
unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup FCG_Global_Functions\n @{"]
    pub fn FCG_Fcg0PeriphClockCmd(u32Fcg0Periph: u32, enNewState: en_functional_state_t);
    pub fn FCG_Fcg1PeriphClockCmd(u32Fcg1Periph: u32, enNewState: en_functional_state_t);
    pub fn FCG_Fcg2PeriphClockCmd(u32Fcg2Periph: u32, enNewState: en_functional_state_t);
    pub fn FCG_Fcg3PeriphClockCmd(u32Fcg3Periph: u32, enNewState: en_functional_state_t);
}
