/* automatically generated by rust-bindgen 0.72.1 */

pub const AES_KEY_SIZE_16BYTE: u32 = 16;
unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup AES_Global_Functions\n @{"]
    pub fn AES_Encrypt(
        pu8Plaintext: *const u8,
        u32PlaintextSize: u32,
        pu8Key: *const u8,
        u8KeySize: u8,
        pu8Ciphertext: *mut u8,
    ) -> i32;
    pub fn AES_Decrypt(
        pu8Ciphertext: *const u8,
        u32CiphertextSize: u32,
        pu8Key: *const u8,
        u8KeySize: u8,
        pu8Plaintext: *mut u8,
    ) -> i32;
    pub fn AES_DeInit() -> i32;
}
