/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup HASH_Global_Functions\n @{"]
    pub fn HASH_DeInit() -> i32;
    pub fn HASH_Calculate(pu8SrcData: *const u8, u32SrcDataSize: u32, pu8MsgDigest: *mut u8)
        -> i32;
}
