/* automatically generated by rust-bindgen 0.72.1 */

pub const SWDT_FLAG_UDF: u32 = 65536;
pub const SWDT_FLAG_REFRESH: u32 = 131072;
pub const SWDT_FLAG_ALL: u32 = 196608;
pub const en_flag_status_t_RESET: en_flag_status_t = 0;
pub const en_flag_status_t_SET: en_flag_status_t = 1;
#[doc = " @brief Flag status"]
pub type en_flag_status_t = ::core::ffi::c_uint;
unsafe extern "C" {
    pub fn SWDT_FeedDog();
    pub fn SWDT_GetStatus(u32Flag: u32) -> en_flag_status_t;
    pub fn SWDT_ClearStatus(u32Flag: u32) -> i32;
}
