/* automatically generated by rust-bindgen 0.72.1 */

pub const DBGC_PERIPH_SWDT: u32 = 1;
pub const DBGC_PERIPH_WDT: u32 = 2;
pub const DBGC_PERIPH_RTC: u32 = 4;
pub const DBGC_PERIPH_TMR0_1: u32 = 16384;
pub const DBGC_PERIPH_TMR0_2: u32 = 32768;
pub const DBGC_PERIPH_TMR4_1: u32 = 1048576;
pub const DBGC_PERIPH_TMR4_2: u32 = 2097152;
pub const DBGC_PERIPH_TMR4_3: u32 = 4194304;
pub const DBGC_PERIPH_TMR6_1: u32 = 8388608;
pub const DBGC_PERIPH_TMR6_2: u32 = 16777216;
pub const DBGC_PERIPH_TMR6_3: u32 = 33554432;
pub const DBGC_PERIPH_TMRA_1: u32 = 67108864;
pub const DBGC_PERIPH_TMRA_2: u32 = 134217728;
pub const DBGC_PERIPH_TMRA_3: u32 = 268435456;
pub const DBGC_PERIPH_TMRA_4: u32 = 536870912;
pub const DBGC_PERIPH_TMRA_5: u32 = 1073741824;
pub const DBGC_PERIPH_TMRA_6: u32 = 2147483648;
pub const DBGC_TRACE_ASYNC: u32 = 0;
pub const DBGC_TRACE_SYNC_1BIT: u32 = 1;
pub const DBGC_TRACE_SYNC_2BIT: u32 = 2;
pub const DBGC_TRACE_SYNC_4BIT: u32 = 3;
pub const en_functional_state_t_DISABLE: en_functional_state_t = 0;
pub const en_functional_state_t_ENABLE: en_functional_state_t = 1;
#[doc = " @brief Functional state"]
pub type en_functional_state_t = ::core::ffi::c_uint;
unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup DBGC_Global_Functions\n @{"]
    pub fn DBGC_PeriphCmd(u32Periph: u32, enNewState: en_functional_state_t);
    pub fn DBGC_TraceIoCmd(enNewState: en_functional_state_t);
    pub fn DBGC_TraceModeConfig(u32TraceMode: u32);
}
