/* automatically generated by rust-bindgen 0.72.1 */

pub const RMU_FLAG_PWR_ON: u32 = 1;
pub const RMU_FLAG_PIN: u32 = 2;
pub const RMU_FLAG_BROWN_OUT: u32 = 4;
pub const RMU_FLAG_PVD1: u32 = 8;
pub const RMU_FLAG_PVD2: u32 = 16;
pub const RMU_FLAG_WDT: u32 = 32;
pub const RMU_FLAG_SWDT: u32 = 64;
pub const RMU_FLAG_PWR_DOWN: u32 = 128;
pub const RMU_FLAG_SW: u32 = 256;
pub const RMU_FLAG_MPU_ERR: u32 = 512;
pub const RMU_FLAG_RAM_PARITY_ERR: u32 = 1024;
pub const RMU_FLAG_RAM_ECC: u32 = 2048;
pub const RMU_FLAG_CLK_ERR: u32 = 4096;
pub const RMU_FLAG_XTAL_ERR: u32 = 8192;
pub const RMU_FLAG_MX: u32 = 16384;
pub const RMU_FLAG_ALL: u32 = 32767;
pub const en_flag_status_t_RESET: en_flag_status_t = 0;
pub const en_flag_status_t_SET: en_flag_status_t = 1;
#[doc = " @brief Flag status"]
pub type en_flag_status_t = ::core::ffi::c_uint;
unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup RMU_Global_Functions\n @{"]
    pub fn RMU_GetStatus(u32RmuResetCause: u32) -> en_flag_status_t;
    pub fn RMU_ClearStatus();
}
