/* automatically generated by rust-bindgen 0.72.1 */

pub const TRNG_RELOAD_INIT_VAL_ENABLE: u32 = 1;
pub const TRNG_RELOAD_INIT_VAL_DISABLE: u32 = 0;
pub const TRNG_SHIFT_CNT32: u32 = 12;
pub const TRNG_SHIFT_CNT64: u32 = 16;
pub const TRNG_SHIFT_CNT128: u32 = 20;
pub const TRNG_SHIFT_CNT256: u32 = 24;
pub const en_functional_state_t_DISABLE: en_functional_state_t = 0;
pub const en_functional_state_t_ENABLE: en_functional_state_t = 1;
#[doc = " @brief Functional state"]
pub type en_functional_state_t = ::core::ffi::c_uint;
unsafe extern "C" {
    #[doc = "Global function prototypes (definition in C source)\n/\n/**\n @addtogroup TRNG_Global_Functions\n @{"]
    pub fn TRNG_DeInit() -> i32;
    pub fn TRNG_Init(u32ShiftCount: u32, u32ReloadInitValueEn: u32);
    pub fn TRNG_GenerateRandom(pu32Random: *mut u32, u32RandomLen: u32) -> i32;
    pub fn TRNG_Start();
    pub fn TRNG_Cmd(enNewState: en_functional_state_t);
    pub fn TRNG_GetRandom(pu32Random: *mut u32, u8RandomLen: u8) -> i32;
}
