[package]
name = "hc32f460_driver_sys"
version = "0.1.1"
edition = "2024"
description = "Provide driver function binding for HDSC's HC32F460 MCU."
keywords = ["HC32", "bindgen", "no_std", "bare-metal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/823984418/hc32_driver_sys"
exclude = [
    "build",
    "driver",
]

[dependencies]

[lints.rust]
nonstandard_style = "allow"
unpredictable_function_pointer_comparisons = "allow"
