[package]
name = "hc32f448_driver_sys"
version = "0.2.0"
edition = "2024"
description = "Provide driver function binding for HDSC's HC32F448 MCU."
keywords = ["HC32", "bindgen", "no_std", "bare-metal"]
categories = ["embedded", "hardware-support", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/823984418/hc32_driver_sys"
exclude = [
    "build",
    "driver",
]

[lib]

[dependencies]

[lints.rust]
nonstandard_style = "allow"
unpredictable_function_pointer_comparisons = "allow"
